version: '3'
services:
  db:
    image: mysql:5.7.24
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
      MYSQL_USER: adminUser
      MYSQL_PASSWORD: adminPassword
    volumes:
      - ./store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  store:
